spring.application.name=step12-boot-jpa

# JPA 설정
# upadate : 변경된 컬럼 추가(기존데이터가 유지), create : 매번 재생성
spring.jpa.hibernate.ddl-auto=create
# 실행 SQL 콘솔 출력(작업용, 운영할떄는 false)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# 서버 포트 설정 (기본 8080 대신 8888 사용)
server.port=8888

# Thymeleaf 설정
# 개발 시 수정사항을 즉시 확인하기 위해 캐시를 끕니다.
spring.thymeleaf.cache=false

# MySQL 데이터베이스 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/kiosk_db
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver